### ISSUE TITLE
Selected text colour poor or non-existent

### ISSUE THREAD

**Issue by ludasmokva** [diomed/glacier4brackets#2]
Really great theme. Congrats!
Only issue so far (just started using it) is that the selected text colour is very poor. I can't even tell that it is selected. The only way I know is that when I start typing I see that it is replaced.
Please update. In the mean time will switch to another template. But I really like this one. Clear, bright, but not glaring.

**Comment by diomed** [comment]
yup. found it. I made it bright yellow. oh gosh, oh gosh.
updated now. 
Thanks for reporting.
