### ISSUE TITLE
broken: editor font change

### ISSUE THREAD

**Issue by sai-chai** [diomed/glacier4brackets#3]
Haven't opened Brackets in a couple months and the editor font size is now fixed at something ridiculous like 22px. It's not changing at all. The only thing that changes it is when I reload without extensions, which of course removes Glacier.

**Comment by diomed** [comment]
ok. I'll look into it. apparently something's changed and template upon which I built all my themes is now changing different property than before. how weird. 
thanks for reporting.

**Comment by sai-chai** [comment]
Yeah I think I know what's wrong. In theme.less, at line 80, the version that's on Adobe's servers has the font-size set permanently to 18px. That line should be deleted outright. Oddly enough, the error doesn't show up on the theme.less file in this repository. Weird.

**Comment by diomed** [comment]
coz I've just updated it. :)

but yeah, that's the apparently new error. worked fine last time I checked, but I also didnt open Brackets too long. I'll add some nicer background highlighting as well and update theme.
